info: Server started at http://localhost:2000/api/v1/ {"timestamp":"2023-02-02T04:26:48.190Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:26:52.327Z"}
info: Server started at http://localhost:2000/api/v1/ {"timestamp":"2023-02-02T04:28:06.077Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:28:09.561Z"}
error: 
    status - 500 
    message - ValidationError: "fName" is required 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2023-02-02T04:28:35.980Z"}
info: Server started at http://localhost:2000/api/v1/ {"timestamp":"2023-02-02T04:34:47.875Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:34:51.912Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:36:11.569Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:36:15.092Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (F:\FundooNotes\FundooApp\src\middlewares\/auth.middleware.js:25:28)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:36:27.497Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:37:50.926Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:37:54.713Z"}
error: 
    status - 500 
    message - ReferenceError: userdata is not defined
    at _callee$ (F:\FundooNotes\FundooApp\src\middlewares\/auth.middleware.js:25:23)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:38:00.907Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:39:05.236Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:39:08.731Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (F:\FundooNotes\FundooApp\src\middlewares\/auth.middleware.js:25:32)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:39:11.848Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (F:\FundooNotes\FundooApp\src\middlewares\/auth.middleware.js:25:32)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:39:17.667Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:41:26.957Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:41:31.097Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:42:09.287Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:42:13.895Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:43:30.221Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:43:33.852Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:45:00.828Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:45:04.623Z"}
error: 
    status - 500 
    message - TypeError: Cannot read properties of undefined (reading 'email')
    at _callee$ (F:\FundooNotes\FundooApp\src\middlewares\/auth.middleware.js:25:32)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:45:08.736Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:46:53.110Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:46:56.622Z"}
error: 
    status - 500 
    message - Error: CastError: Cast to ObjectId failed for value "{ id: '63db3cf9b521202754eb5498', userId: 'helloworld@gmail.com' }" (type Object) at path "_id" for model "Note"
    at _callee6$ (F:\FundooNotes\FundooApp\src\services\/note.service.js:52:13)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:47:01.161Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:51:32.990Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:51:36.889Z"}
error: 
    status - 500 
    message - Error: CastError: Cast to ObjectId failed for value "{ id: '63db3cf9b521202754eb5498', userId: 'helloworld@gmail.com' }" (type Object) at path "_id" for model "Note"
    at _callee6$ (F:\FundooNotes\FundooApp\src\services\/note.service.js:52:13)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:51:44.962Z"}
error: 
    status - 500 
    message - Error: CastError: Cast to ObjectId failed for value "{ id: '63db3cf9b521202754eb5498', userId: 'helloworld@gmail.com' }" (type Object) at path "_id" for model "Note"
    at _callee6$ (F:\FundooNotes\FundooApp\src\services\/note.service.js:52:13)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:51:51.446Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:53:18.921Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:53:22.400Z"}
error: 
    status - 500 
    message - Error: CastError: Cast to ObjectId failed for value "{ id: '63db3cf9b521202754eb5498', userId: 'helloworld@gmail.com' }" (type Object) at path "_id" for model "Note"
    at _callee6$ (F:\FundooNotes\FundooApp\src\services\/note.service.js:52:13)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:53:26.849Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:55:27.739Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:55:31.653Z"}
error: 
    status - 500 
    message - Error: CastError: Cast to ObjectId failed for value "{ _id: undefined, userId: 'helloworld@gmail.com' }" (type Object) at path "_id" for model "Note"
    at _callee6$ (F:\FundooNotes\FundooApp\src\services\/note.service.js:52:13)
    at tryCatch (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (F:\FundooNotes\FundooApp\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) 
    url - /api/v1/notes/trash/63db3cf9b521202754eb5498 
    method - PUT 
    IP - ::1
   {"timestamp":"2023-02-02T04:55:35.692Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:56:36.619Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:56:40.820Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:58:32.155Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:58:36.680Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:58:59.739Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:59:03.577Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T04:59:28.250Z"}
info: Connected to the database. {"timestamp":"2023-02-02T04:59:32.363Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2023-02-02T05:08:27.754Z"}
info: Connected to the database. {"timestamp":"2023-02-02T05:08:31.423Z"}
